export const ProductListData = [
  {
    id: "1",
    name: "Ergonomic Phone Stand",
    imageSrc: "/",
    imageAlt: "Black metal phone stande",
    category: "Accessories",
    rating: 4.8,
    reviewCount: 1200,
    price: 29.9,
  },
  {
    id: "2",
    name: "Wireless Headphones Pro X",
    imageSrc: "/",
    imageAlt: "White wireless headphones",
    category: "Electronics",
    rating: 5.0,
    reviewCount: 850,
    price: 199.99,
  },
  {
    id: "3",
    name: "Smartwatch FitPulse",
    imageSrc: "/",
    imageAlt: "Smartwatch on wrist",
    category: "Gadgets",
    rating: 4.5,
    reviewCount: 230,
    price: 125.5,
  },
  {
    id: "4",
    name: "Portable Speaker Soundwave",
    imageSrc: "/",
    imageAlt: "Soundwave speaker",
    category: "Audio",
    rating: 4.2,
    reviewCount: 45,
    price: 75.0,
  },
  {
    id: "5",
    name: "PowerFlow Charger",
    imageSrc: "/",
    imageAlt: "Phone charger",
    category: "Accessories",
    rating: 4.9,
    reviewCount: 560,
    price: 35.75,
  },

  {
    id: "6",
    name: "Laptop Cooling Pad",
    imageSrc: "/",
    imageAlt: "Laptop cooling pad with fan",
    category: "Accessories",
    rating: 4.3,
    reviewCount: 310,
    price: 49.99,
  },
  {
    id: "7",
    name: "Noise Cancelling Earbuds",
    imageSrc: "/",
    imageAlt: "Black noise cancelling earbuds",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 720,
    price: 89.5,
  },
  {
    id: "8",
    name: "Fitness Tracker Band",
    imageSrc: "/",
    imageAlt: "Fitness tracker on wrist",
    category: "Gadgets",
    rating: 4.1,
    reviewCount: 150,
    price: 59.99,
  },
  {
    id: "9",
    name: "Bluetooth Portable Speaker",
    imageSrc: "/",
    imageAlt: "Compact bluetooth speaker",
    category: "Audio",
    rating: 4.6,
    reviewCount: 200,
    price: 65.0,
  },
  {
    id: "10",
    name: "Fast Wireless Charger",
    imageSrc: "/",
    imageAlt: "Fast wireless charger for phone",
    category: "Accessories",
    rating: 4.8,
    reviewCount: 410,
    price: 39.99,
  },
];
