import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import { ILayout } from '@/types/ILayout';
import { QueryProvider } from '@/components/providers/QueryProvider';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ILayout) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${quicksand.variable} flex min-h-screen flex-col overflow-x-hidden bg-white text-gray-900 antialiased`}
      >
        <QueryProvider>
          <Header />
          <main className="flex flex-1">{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
