import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';

import { cn } from '@/utils/cn';
import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import { QueryProvider } from '@/components/providers/QueryProvider';
import type { ILayout } from '@/types/ILayout';

import './globals.css';

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * @remarks
 * Root layout component for the application.
 * Provides global fonts, header, footer, and query context.
 */
export function RootLayout({ children }: ILayout) {
  return (
    <html lang="en" className={cn('overflow-x-hidden')}>
      <body
        className={cn(
          quicksand.variable,
          'flex min-h-screen flex-col overflow-x-hidden bg-white text-gray-900 antialiased'
        )}
      >
        <QueryProvider>
          <Header />
          <main className={cn('flex flex-1')}>{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
