import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import { cn } from '@/lib/utils/cn';

import QueryProvider from '@/app/_providers/QueryProvider';
import Footer from './_components/MainFooter';
import Header from './_components/MainHeader';
import '@/styles/globals.css';

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface MainLayout {
  children: React.ReactNode;
}

/**
 * @remarks
 * Root layout component for the application.
 * Provides global fonts, header, footer, and query context.
 */
export function MainLayout({ children }: MainLayout) {
  return (
    <html lang="en" className={cn('overflow-x-hidden')}>
      <body
        className={cn(
          quicksand.variable,
          'flex min-h-screen flex-col overflow-x-hidden bg-white text-gray-900 antialiased'
        )}
      >
        <QueryProvider>
          <Header />
          <main className={cn('flex flex-1')}>{children}</main>
          <Footer />
          <Toaster position="top-right" reverseOrder={false} />
        </QueryProvider>
      </body>
    </html>
  );
}

export default MainLayout;
